import React, { createContext, useContext, useState, useEffect } from 'react';
import { doc, getDoc, onSnapshot } from 'firebase/firestore';
import { db } from '../database/firebase';

import DefaultLogo from '../assets/logo/barangay buluan seal.png';

const SettingsContext = createContext();

export function useSettings() {
  return useContext(SettingsContext);
}

export function SettingsProvider({ children }) {
  const [settings, setSettings] = useState({
    logoUrl: DefaultLogo,
    barangayName: 'Barangay Buluan',
    barangayNameShort: 'Brgy. Buluan',
    address: 'Buluan, Ipil, Zamboanga Sibugay',
    zipCode: '7025',
    contactNumber: '0912 345 6789',
    emailAddress: 'barangaybuluan@gmail.com',
    officialWebsite: 'https://barangaybuluan.gov.ph',
    officeHours: 'Monday - Friday 8:00 AM - 5:00 PM',
    lunchBreak: '12:00 PM - 1:00 PM',
    holidaySchedule: 'Follow Regular Holidays',
    captain: 'Hon. Juan Dela Cruz',
    footerNote: 'This is an official document generated by the Barangay Buluan Request System. No signature is required.',
    defaultReleaseMethod: 'Pick up at Barangay Hall',
    documents: [
      {
        id: 'barangay_clearance',
        title: '1. Barangay Clearance',
        desc: 'Requirements: Purok Clearance, Valid ID, Required Age 18+',
        firstCopyFee: '100.00',
        additionalCopyFee: '10.00',
        processingTime: '1 - 2 Working Days',
        status: 'active'
      },
      {
        id: 'certificate_of_residency',
        title: '2. Certificate of Residency',
        desc: 'Requirements: Purok Clearance (₱25), Required Age 18+',
        firstCopyFee: '100.00',
        additionalCopyFee: '10.00',
        processingTime: '1 - 2 Working Days',
        status: 'active'
      },
      {
        id: 'certificate_of_indigency',
        title: '3. Certificate of Indigency',
        desc: 'Cedula is required for 18 years old and above. Minors (below 18) are not required to upload a Cedula.',
        firstCopyFee: '5.00',
        additionalCopyFee: '10.00',
        processingTime: '1 - 2 Working Days',
        status: 'active'
      },
      {
        id: 'business_clearance',
        title: '4. Business Permit',
        desc: 'Requirements: Valid ID, Old/New Business Permit',
        firstCopyFee: '300.00',
        additionalCopyFee: '20.00',
        processingTime: '1 - 2 Working Days',
        status: 'active'
      }
    ],
    notificationSettings: {
      resident_req_confirmation: true,
      resident_req_approved: true,
      resident_req_rejected: true,
      resident_req_ready: true,
      resident_req_cancelled: true,
      admin_new_registration: true,
      admin_new_request: true,
      admin_new_payment: true,
      admin_new_message: true,
      security_failed_login: true,
    }
  });
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // We use onSnapshot to listen for real-time updates to settings
    const docRef = doc(db, 'settings', 'general');
    
    const unsubscribe = onSnapshot(docRef, (docSnap) => {
      if (docSnap.exists()) {
        const data = docSnap.data();
        if (data.documents && Array.isArray(data.documents)) {
          data.documents = data.documents.map(d => {
            if (d.id === 'business_clearance' || d.title?.includes('Business Clearance')) {
              return { ...d, title: '4. Business Permit' };
            }
            return d;
          });
        }
        setSettings(prev => ({ ...prev, ...data }));
      }
      setLoading(false);
    }, (error) => {
      console.error("Error fetching settings:", error);
      setLoading(false);
    });

    return () => unsubscribe();
  }, []);

  const updatePreview = (newSettings) => {
    setSettings(prev => ({ ...prev, ...newSettings }));
  };

  const value = {
    settings,
    loading,
    updatePreview
  };

  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  );
}
